### ISSUE TITLE
Errors and deprecations

### ISSUE THREAD

**Issue by dmitriz** [kparc/ref#17]
Getting this error:

```sh
~ npm run build
... <all tests are ok> ...
...
Loading "Gruntfile.js" tasks...ERROR
>> invalid snippets detected
Warning: Task "default" not found. Use --force to continue.

Aborted due to warnings.
npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! @kparc/ref@1.1.0 build: `grunt`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the @kparc/ref@1.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dmitrizaitsev/.npm/_logs/2019-07-26T03_49_11_024Z-debug.log
```

Might be due to some outdated deps, e.g. this one had been deprecated:
https://www.npmjs.com/package/grunt-contrib-uglify-es

**Comment by dmitriz** [comment]
> 'However, they do some steps in the false direction, like making a difference between verbs and functions.'
<https://vector.org.uk/a-modern-apl-system/>
<sub>[View in Slack](https://kparc.slack.com/archives/GLEPLBVMX/p1563910321392300)</sub>

**Comment by gitonthescene** [comment]
I'm not sure it's the same issue, but I'm getting this today on osX 12.0.1 (Monterey)

```
82 verbose stack Error: @kparc/k@2.0.70 preinstall: `npm run build --silent`
82 verbose stack Exit status 1
82 verbose stack     at EventEmitter.<anonymous> (/opt/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
82 verbose stack     at EventEmitter.emit (node:events:390:28)
82 verbose stack     at ChildProcess.<anonymous> (/opt/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
82 verbose stack     at ChildProcess.emit (node:events:390:28)
82 verbose stack     at maybeClose (node:internal/child_process:1064:16)
82 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
83 verbose pkgid @kparc/k@2.0.70
84 verbose cwd /Users/douglasmennella/bin
85 verbose Darwin 21.1.0
86 verbose argv "/opt/local/bin/node" "/opt/local/bin/npm" "i" "@kparc/k"
87 verbose node v16.13.1
88 verbose npm  v6.14.15
89 error code ELIFECYCLE
90 error errno 1
91 error @kparc/k@2.0.70 preinstall: `npm run build --silent`
91 error Exit status 1
92 error Failed at the @kparc/k@2.0.70 preinstall script.
92 error This is probably not a problem with npm. There is likely additional logging output above.
93 verbose exit [ 1, true ]
```

There's not a lot more useful that I can spot in the log.  This probably:

```
74 silly lifecycle @kparc/k@2.0.70~preinstall: Returned: code: 1  signal: null
75 info lifecycle @kparc/k@2.0.70~preinstall: Failed to exec preinstall script
```
